# $Id: cfengine-pgs.spec,v 1.6 2011/09/26 20:22:18 lcerezo Exp $
# Authority: pgs

Summary: Tomcat 7 build for viasat
Name: tomcat7-el6-viasat
Version: 0.0.1
Release: 1
URL: http://itrack.prod.wdc1.wildblue.net/confluence/display/t4sys/Home
License: GPL
Group: Utilities/System
BuildArch: noarch
Requires: java-1.6.0-openjdk, java-1.6.0-openjdk-devel
BuildRoot: /tmp/rpm/%{name}-root/
Packager: Luis E. Cerezo (luis.cerezo@viasat.com) (+1 412 223 7396)

%description
This package installs tomcat7 with the specific configs for ViaSat Exede.
%define _rpmdir /tmp/rpm/
%install
%pre
/usr/bin/getent group tomcat7 || grouadd -r tomcat7
/usr/bin/getent passwd tomcat7 || useradd -r -g tomcat7 -d /apps/tomcat7 -s /sbin/nologin -c "tomcat 7 service account for ViaSat Apps" tomcat7
exit 0

%preun
/usr/sbin/userdel tomcat7
/usr/sbin/chkconfig --del tomcat7
%post
/sbin/chkconfig --add tomcat7
/sbin/chkconfig tomcat7 on
%files
%defattr(774,root,root)
/apps/tomcat/certs
/apps/tomcat/certs/PSSSUBCERT01.cer
/apps/tomcat/certs/PSSRTROOTCA.cer
/apps/tomcat/certs/PSSSUBCERT02.cer
/apps
/apps/apache-tomcat-7.0.40
/apps/apache-tomcat-7.0.40/work
/apps/apache-tomcat-7.0.40/webapps
/apps/apache-tomcat-7.0.40/webapps/host-manager
/apps/apache-tomcat-7.0.40/webapps/host-manager/META-INF
/apps/apache-tomcat-7.0.40/webapps/host-manager/META-INF/context.xml
/apps/apache-tomcat-7.0.40/webapps/host-manager/manager.xml
/apps/apache-tomcat-7.0.40/webapps/host-manager/WEB-INF
/apps/apache-tomcat-7.0.40/webapps/host-manager/WEB-INF/web.xml
/apps/apache-tomcat-7.0.40/webapps/host-manager/WEB-INF/jsp
/apps/apache-tomcat-7.0.40/webapps/host-manager/WEB-INF/jsp/404.jsp
/apps/apache-tomcat-7.0.40/webapps/host-manager/WEB-INF/jsp/401.jsp
/apps/apache-tomcat-7.0.40/webapps/host-manager/WEB-INF/jsp/403.jsp
/apps/apache-tomcat-7.0.40/webapps/host-manager/index.jsp
/apps/apache-tomcat-7.0.40/webapps/host-manager/images
/apps/apache-tomcat-7.0.40/webapps/host-manager/images/design.gif
/apps/apache-tomcat-7.0.40/webapps/host-manager/images/void.gif
/apps/apache-tomcat-7.0.40/webapps/host-manager/images/asf-logo.gif
/apps/apache-tomcat-7.0.40/webapps/host-manager/images/fix.gif
/apps/apache-tomcat-7.0.40/webapps/host-manager/images/tomcat.gif
/apps/apache-tomcat-7.0.40/webapps/host-manager/images/docs.gif
/apps/apache-tomcat-7.0.40/webapps/host-manager/images/update.gif
/apps/apache-tomcat-7.0.40/webapps/host-manager/images/code.gif
/apps/apache-tomcat-7.0.40/webapps/host-manager/images/add.gif
/apps/apache-tomcat-7.0.40/webapps/examples
/apps/apache-tomcat-7.0.40/webapps/examples/servlets
/apps/apache-tomcat-7.0.40/webapps/examples/servlets/reqheaders.html
/apps/apache-tomcat-7.0.40/webapps/examples/servlets/sessions.html
/apps/apache-tomcat-7.0.40/webapps/examples/servlets/cookies.html
/apps/apache-tomcat-7.0.40/webapps/examples/servlets/helloworld.html
/apps/apache-tomcat-7.0.40/webapps/examples/servlets/reqparams.html
/apps/apache-tomcat-7.0.40/webapps/examples/servlets/index.html
/apps/apache-tomcat-7.0.40/webapps/examples/servlets/images
/apps/apache-tomcat-7.0.40/webapps/examples/servlets/images/return.gif
/apps/apache-tomcat-7.0.40/webapps/examples/servlets/images/execute.gif
/apps/apache-tomcat-7.0.40/webapps/examples/servlets/images/code.gif
/apps/apache-tomcat-7.0.40/webapps/examples/servlets/reqinfo.html
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/tags
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/tags/xhtmlbasic.tag
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/tags/displayProducts.tag
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/tags/helloWorld.tag
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/tags/panel.tag
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/web.xml
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/jsp2
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/jsp2/jsp2-example-taglib.tld
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/lib
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/lib/jstl.jar
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/lib/standard.jar
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/jsp
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/jsp/debug-taglib.tld
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/jsp/applet
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/jsp/applet/Clock2.java
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/jsp/example-taglib.tld
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/RequestParamExample.java
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/RequestHeaderExample.java
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/filters
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/filters/ExampleFilter.class
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/filters/ExampleFilter.java
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/async
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/async/Async0.java
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/async/Async2$1.class
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/async/AsyncStockServlet.class
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/async/Stockticker.java
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/async/Stockticker$TickListener.class
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/async/Async0$1.class
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/async/AsyncStockServlet.java
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/async/Async1.java
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/async/Async1.class
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/async/Async1$1.class
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/async/Async2.class
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/async/Async3.class
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/async/Async3.java
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/async/Async0.class
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/async/Stockticker$Stock.class
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/async/Stockticker.class
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/async/Async2.java
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/ServletToJsp.java
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/error
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/error/Smart.class
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/error/Smart.java
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/dates
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/dates/JspCalendar.java
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/dates/JspCalendar.class
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/cal
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/cal/JspCalendar.java
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/cal/Entries.class
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/cal/Entries.java
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/cal/JspCalendar.class
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/cal/TableBean.class
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/cal/Entry.java
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/cal/TableBean.java
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/cal/Entry.class
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/LocalStrings_en.properties
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/validators
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/validators/DebugValidator.java
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/validators/DebugValidator.class
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/LocalStrings_fr.properties
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/checkbox
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/checkbox/CheckTest.class
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/checkbox/CheckTest.java
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/HelloWorldExample.class
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/util
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/util/HTMLFilter.class
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/util/HTMLFilter.java
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/compressionFilters
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/compressionFilters/CompressionFilterTestServlet.class
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/compressionFilters/CompressionFilter.java
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/compressionFilters/CompressionResponseStream.java
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/compressionFilters/CompressionResponseStream.class
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/compressionFilters/CompressionFilterTestServlet.java
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/compressionFilters/CompressionServletResponseWrapper.class
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/compressionFilters/CompressionServletResponseWrapper.java
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/compressionFilters/CompressionFilter.class
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/CookieExample.java
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/RequestInfoExample.class
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/num
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/num/NumberGuessBean.java
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/num/NumberGuessBean.class
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/jsp2
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/jsp2/examples
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/jsp2/examples/BookBean.class
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/jsp2/examples/simpletag
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/jsp2/examples/simpletag/RepeatSimpleTag.java
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/jsp2/examples/simpletag/TileSimpleTag.java
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/jsp2/examples/simpletag/FindBookSimpleTag.class
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/jsp2/examples/simpletag/FindBookSimpleTag.java
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/jsp2/examples/simpletag/EchoAttributesTag.class
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/jsp2/examples/simpletag/HelloWorldSimpleTag.class
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/jsp2/examples/simpletag/TileSimpleTag.class
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/jsp2/examples/simpletag/ShuffleSimpleTag.java
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/jsp2/examples/simpletag/HelloWorldSimpleTag.java
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/jsp2/examples/simpletag/RepeatSimpleTag.class
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/jsp2/examples/simpletag/EchoAttributesTag.java
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/jsp2/examples/simpletag/ShuffleSimpleTag.class
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/jsp2/examples/BookBean.java
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/jsp2/examples/el
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/jsp2/examples/el/Functions.java
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/jsp2/examples/el/Functions.class
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/jsp2/examples/FooBean.java
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/jsp2/examples/ValuesBean.java
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/jsp2/examples/FooBean.class
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/jsp2/examples/ValuesBean.class
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/examples
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/examples/FooTagExtraInfo.class
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/examples/ValuesTag.class
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/examples/LogTag.class
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/examples/FooTag.class
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/examples/ExampleTagBase.class
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/examples/FooTag.java
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/examples/FooTagExtraInfo.java
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/examples/ExampleTagBase.java
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/examples/ShowSource.class
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/examples/ShowSource.java
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/examples/LogTag.java
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/examples/ValuesTag.java
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/LocalStrings.properties
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/websocket
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/websocket/snake
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/websocket/snake/SnakeWebSocketServlet.java
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/websocket/snake/SnakeWebSocketServlet$1.class
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/websocket/snake/SnakeWebSocketServlet.class
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/websocket/snake/SnakeWebSocketServlet$SnakeMessageInbound.class
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/websocket/snake/Location.java
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/websocket/snake/Direction.class
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/websocket/snake/Snake.class
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/websocket/snake/Location$1.class
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/websocket/snake/Direction.java
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/websocket/snake/Snake.java
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/websocket/snake/Location.class
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/websocket/chat
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/websocket/chat/ChatWebSocketServlet$ChatMessageInbound.class
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/websocket/chat/ChatWebSocketServlet$1.class
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/websocket/chat/ChatWebSocketServlet.class
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/websocket/chat/ChatWebSocketServlet.java
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/websocket/echo
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/websocket/echo/EchoStream$1.class
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/websocket/echo/EchoMessage.class
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/websocket/echo/EchoStream.class
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/websocket/echo/EchoMessage.java
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/websocket/echo/EchoStream.java
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/websocket/echo/EchoMessage$EchoMessageInbound.class
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/websocket/echo/EchoStream$EchoStreamInbound.class
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/listeners
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/listeners/ContextListener.java
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/listeners/SessionListener.class
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/listeners/ContextListener.class
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/listeners/SessionListener.java
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/SessionExample.java
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/LocalStrings_es.properties
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/CookieExample.class
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/HelloWorldExample.java
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/RequestParamExample.class
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/ServletToJsp.class
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/LocalStrings_pt.properties
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/RequestHeaderExample.class
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/colors
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/colors/ColorGameBean.java
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/colors/ColorGameBean.class
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/sessions
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/sessions/DummyCart.java
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/sessions/DummyCart.class
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/chat
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/chat/ChatServlet.java
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/chat/ChatServlet$MessageSender.class
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/chat/ChatServlet.class
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/RequestInfoExample.java
/apps/apache-tomcat-7.0.40/webapps/examples/WEB-INF/classes/SessionExample.class
/apps/apache-tomcat-7.0.40/webapps/examples/index.html
/apps/apache-tomcat-7.0.40/webapps/examples/websocket
/apps/apache-tomcat-7.0.40/webapps/examples/websocket/chat.html
/apps/apache-tomcat-7.0.40/webapps/examples/websocket/echo.html
/apps/apache-tomcat-7.0.40/webapps/examples/websocket/snake.html
/apps/apache-tomcat-7.0.40/webapps/examples/websocket/index.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/forward
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/forward/one.jsp.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/forward/two.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/forward/forward.jsp.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/forward/forward.jsp
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/forward/fwd.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/forward/one.jsp
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/async
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/async/async3.jsp.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/async/async3.jsp
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/async/async1.jsp
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/async/index.jsp
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/async/index.jsp.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/async/async1.jsp.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/error
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/error/er.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/error/errorpge.jsp.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/error/errorpge.jsp
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/error/err.jsp.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/error/err.jsp
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/error/error.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/source.jsp
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/simpletag
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/simpletag/foo.jsp
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/simpletag/foo.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/simpletag/foo.jsp.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/dates
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/dates/date.jsp
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/dates/date.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/dates/date.jsp.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/cal
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/cal/Entry.java.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/cal/JspCalendar.java.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/cal/cal2.jsp
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/cal/cal1.jsp
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/cal/TableBean.java.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/cal/cal2.jsp.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/cal/cal1.jsp.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/cal/Entries.java.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/cal/login.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/cal/calendar.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/checkbox
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/checkbox/checkresult.jsp.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/checkbox/CheckTest.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/checkbox/checkresult.jsp
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/checkbox/check.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/checkbox/cresult.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/xml
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/xml/xml.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/xml/xml.jsp
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/xml/xml.jsp.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/num
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/num/numguess.jsp.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/num/numguess.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/num/numguess.jsp
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/source.jsp.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/simpletag
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/simpletag/RepeatSimpleTag.java.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/simpletag/Functions.java.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/simpletag/repeat.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/simpletag/BookBean.java.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/simpletag/repeat.jsp
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/simpletag/hello.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/simpletag/hello.jsp.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/simpletag/book.jsp
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/simpletag/HelloWorldSimpleTag.java.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/simpletag/hello.jsp
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/simpletag/book.jsp.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/simpletag/FindBookSimpleTag.java.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/simpletag/repeat.jsp.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/simpletag/book.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/jspattribute
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/jspattribute/FooBean.java.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/jspattribute/ShuffleSimpleTag.java.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/jspattribute/shuffle.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/jspattribute/shuffle.jsp
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/jspattribute/jspattribute.jsp
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/jspattribute/jspattribute.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/jspattribute/TileSimpleTag.java.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/jspattribute/shuffle.jsp.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/jspattribute/jspattribute.jsp.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/jspattribute/HelloWorldSimpleTag.java.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/el
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/el/basic-arithmetic.jsp
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/el/composite.jsp.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/el/basic-comparisons.jsp.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/el/Functions.java.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/el/basic-arithmetic.jsp.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/el/functions.jsp
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/el/implicit-objects.jsp
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/el/composite.jsp
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/el/functions.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/el/implicit-objects.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/el/basic-comparisons.jsp
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/el/implicit-objects.jsp.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/el/functions.jsp.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/el/composite.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/el/ValuesBean.java.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/el/ValuesTag.java.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/el/basic-comparisons.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/el/basic-arithmetic.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/jspx
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/jspx/textRotate.jspx.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/jspx/basic.jspx.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/jspx/basic.jspx
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/jspx/textRotate.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/jspx/svgexample.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/jspx/textRotate.jpg
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/jspx/basic.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/jspx/textRotate.jspx
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/misc
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/misc/config.jsp.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/misc/config.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/misc/coda.jspf.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/misc/dynamicattrs.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/misc/prelude.jspf.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/misc/dynamicattrs.jsp.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/misc/config.jsp
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/misc/dynamicattrs.jsp
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/misc/prelude.jspf
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/misc/EchoAttributesTag.java.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/misc/coda.jspf
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/tagfiles
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/tagfiles/xhtmlbasic.tag.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/tagfiles/panel.jsp
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/tagfiles/products.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/tagfiles/products.jsp
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/tagfiles/helloWorld.tag.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/tagfiles/panel.tag.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/tagfiles/displayProducts.tag.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/tagfiles/panel.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/tagfiles/hello.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/tagfiles/hello.jsp.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/tagfiles/hello.jsp
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/tagfiles/panel.jsp.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsp2/tagfiles/products.jsp.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/index.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/snp
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/snp/snoop.jsp.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/snp/snoop.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/snp/snoop.jsp
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/include
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/include/include.jsp.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/include/include.jsp
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/include/foo.jsp
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/include/foo.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/include/foo.jsp.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/include/inc.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/images
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/images/read.gif
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/images/return.gif
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/images/execute.gif
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/images/code.gif
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsptoserv
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsptoserv/jsptoservlet.jsp
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsptoserv/jts.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsptoserv/ServletToJsp.java.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsptoserv/jsptoservlet.jsp.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsptoserv/hello.jsp.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/jsptoserv/hello.jsp
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/plugin
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/plugin/plugin.jsp
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/plugin/plugin.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/plugin/applet
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/plugin/applet/Clock2.java
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/plugin/applet/Clock2.class
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/plugin/plugin.jsp.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/tagplugin
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/tagplugin/if.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/tagplugin/if.jsp
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/tagplugin/notes.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/tagplugin/choose.jsp.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/tagplugin/howto.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/tagplugin/foreach.jsp.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/tagplugin/choose.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/tagplugin/if.jsp.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/tagplugin/foreach.jsp
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/tagplugin/foreach.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/tagplugin/choose.jsp
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/security
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/security/protected
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/security/protected/login.jsp
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/security/protected/error.jsp
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/security/protected/index.jsp
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/security/protected/index.jsp.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/security/protected/error.jsp.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/security/protected/login.jsp.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/colors
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/colors/ColorGameBean.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/colors/clr.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/colors/colrs.jsp
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/colors/colrs.jsp.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/colors/colors.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/sessions
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/sessions/DummyCart.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/sessions/carts.jsp
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/sessions/carts.jsp.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/sessions/carts.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/sessions/crt.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/chat
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/chat/login.jsp
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/chat/post.jsp
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/chat/index.jsp
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/chat/post.jsp.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/chat/index.jsp.html
/apps/apache-tomcat-7.0.40/webapps/examples/jsp/chat/login.jsp.html
/apps/apache-tomcat-7.0.40/webapps/manager
/apps/apache-tomcat-7.0.40/webapps/manager/status.xsd
/apps/apache-tomcat-7.0.40/webapps/manager/META-INF
/apps/apache-tomcat-7.0.40/webapps/manager/META-INF/context.xml
/apps/apache-tomcat-7.0.40/webapps/manager/WEB-INF
/apps/apache-tomcat-7.0.40/webapps/manager/WEB-INF/web.xml
/apps/apache-tomcat-7.0.40/webapps/manager/WEB-INF/jsp
/apps/apache-tomcat-7.0.40/webapps/manager/WEB-INF/jsp/404.jsp
/apps/apache-tomcat-7.0.40/webapps/manager/WEB-INF/jsp/401.jsp
/apps/apache-tomcat-7.0.40/webapps/manager/WEB-INF/jsp/sessionDetail.jsp
/apps/apache-tomcat-7.0.40/webapps/manager/WEB-INF/jsp/sessionsList.jsp
/apps/apache-tomcat-7.0.40/webapps/manager/WEB-INF/jsp/403.jsp
/apps/apache-tomcat-7.0.40/webapps/manager/xform.xsl
/apps/apache-tomcat-7.0.40/webapps/manager/index.jsp
/apps/apache-tomcat-7.0.40/webapps/manager/images
/apps/apache-tomcat-7.0.40/webapps/manager/images/design.gif
/apps/apache-tomcat-7.0.40/webapps/manager/images/void.gif
/apps/apache-tomcat-7.0.40/webapps/manager/images/asf-logo.gif
/apps/apache-tomcat-7.0.40/webapps/manager/images/fix.gif
/apps/apache-tomcat-7.0.40/webapps/manager/images/tomcat.gif
/apps/apache-tomcat-7.0.40/webapps/manager/images/docs.gif
/apps/apache-tomcat-7.0.40/webapps/manager/images/update.gif
/apps/apache-tomcat-7.0.40/webapps/manager/images/code.gif
/apps/apache-tomcat-7.0.40/webapps/manager/images/add.gif
/apps/apache-tomcat-7.0.40/webapps/ROOT
/apps/apache-tomcat-7.0.40/webapps/ROOT/RELEASE-NOTES.txt
/apps/apache-tomcat-7.0.40/webapps/ROOT/WEB-INF
/apps/apache-tomcat-7.0.40/webapps/ROOT/WEB-INF/web.xml
/apps/apache-tomcat-7.0.40/webapps/ROOT/bg-middle.png
/apps/apache-tomcat-7.0.40/webapps/ROOT/bg-upper.png
/apps/apache-tomcat-7.0.40/webapps/ROOT/bg-nav.png
/apps/apache-tomcat-7.0.40/webapps/ROOT/asf-logo-wide.gif
/apps/apache-tomcat-7.0.40/webapps/ROOT/tomcat.css
/apps/apache-tomcat-7.0.40/webapps/ROOT/tomcat.gif
/apps/apache-tomcat-7.0.40/webapps/ROOT/favicon.ico
/apps/apache-tomcat-7.0.40/webapps/ROOT/index.jsp
/apps/apache-tomcat-7.0.40/webapps/ROOT/tomcat.svg
/apps/apache-tomcat-7.0.40/webapps/ROOT/tomcat-power.gif
/apps/apache-tomcat-7.0.40/webapps/ROOT/bg-button.png
/apps/apache-tomcat-7.0.40/webapps/ROOT/tomcat.png
/apps/apache-tomcat-7.0.40/webapps/ROOT/bg-nav-item.png
/apps/apache-tomcat-7.0.40/webapps/ROOT/asf-logo.png
/apps/apache-tomcat-7.0.40/webapps/ROOT/build.xml
/apps/apache-tomcat-7.0.40/webapps/docs
/apps/apache-tomcat-7.0.40/webapps/docs/funcspecs
/apps/apache-tomcat-7.0.40/webapps/docs/funcspecs/fs-default.html
/apps/apache-tomcat-7.0.40/webapps/docs/funcspecs/fs-jdbc-realm.html
/apps/apache-tomcat-7.0.40/webapps/docs/funcspecs/fs-jndi-realm.html
/apps/apache-tomcat-7.0.40/webapps/docs/funcspecs/index.html
/apps/apache-tomcat-7.0.40/webapps/docs/funcspecs/mbean-names.html
/apps/apache-tomcat-7.0.40/webapps/docs/funcspecs/fs-admin-opers.html
/apps/apache-tomcat-7.0.40/webapps/docs/funcspecs/fs-admin-apps.html
/apps/apache-tomcat-7.0.40/webapps/docs/funcspecs/fs-memory-realm.html
/apps/apache-tomcat-7.0.40/webapps/docs/funcspecs/fs-admin-objects.html
/apps/apache-tomcat-7.0.40/webapps/docs/cluster-howto.html
/apps/apache-tomcat-7.0.40/webapps/docs/virtual-hosting-howto.html
/apps/apache-tomcat-7.0.40/webapps/docs/elapi
/apps/apache-tomcat-7.0.40/webapps/docs/elapi/index.html
/apps/apache-tomcat-7.0.40/webapps/docs/proxy-howto.html
/apps/apache-tomcat-7.0.40/webapps/docs/RELEASE-NOTES.txt
/apps/apache-tomcat-7.0.40/webapps/docs/jdbc-pool.html
/apps/apache-tomcat-7.0.40/webapps/docs/tribes
/apps/apache-tomcat-7.0.40/webapps/docs/tribes/transport.html
/apps/apache-tomcat-7.0.40/webapps/docs/tribes/setup.html
/apps/apache-tomcat-7.0.40/webapps/docs/tribes/introduction.html
/apps/apache-tomcat-7.0.40/webapps/docs/tribes/faq.html
/apps/apache-tomcat-7.0.40/webapps/docs/tribes/status.html
/apps/apache-tomcat-7.0.40/webapps/docs/tribes/developers.html
/apps/apache-tomcat-7.0.40/webapps/docs/tribes/interceptors.html
/apps/apache-tomcat-7.0.40/webapps/docs/tribes/membership.html
/apps/apache-tomcat-7.0.40/webapps/docs/changelog.html
/apps/apache-tomcat-7.0.40/webapps/docs/jndi-datasource-examples-howto.html
/apps/apache-tomcat-7.0.40/webapps/docs/class-loader-howto.html
/apps/apache-tomcat-7.0.40/webapps/docs/manager-howto.html
/apps/apache-tomcat-7.0.40/webapps/docs/mbeans-descriptor-howto.html
/apps/apache-tomcat-7.0.40/webapps/docs/WEB-INF
/apps/apache-tomcat-7.0.40/webapps/docs/WEB-INF/web.xml
/apps/apache-tomcat-7.0.40/webapps/docs/aio.html
/apps/apache-tomcat-7.0.40/webapps/docs/maven-jars.html
/apps/apache-tomcat-7.0.40/webapps/docs/setup.html
/apps/apache-tomcat-7.0.40/webapps/docs/security-manager-howto.html
/apps/apache-tomcat-7.0.40/webapps/docs/default-servlet.html
/apps/apache-tomcat-7.0.40/webapps/docs/jndi-resources-howto.html
/apps/apache-tomcat-7.0.40/webapps/docs/security-howto.html
/apps/apache-tomcat-7.0.40/webapps/docs/web-socket-howto.html
/apps/apache-tomcat-7.0.40/webapps/docs/ssl-howto.html
/apps/apache-tomcat-7.0.40/webapps/docs/RUNNING.txt
/apps/apache-tomcat-7.0.40/webapps/docs/ssi-howto.html
/apps/apache-tomcat-7.0.40/webapps/docs/introduction.html
/apps/apache-tomcat-7.0.40/webapps/docs/windows-auth-howto.html
/apps/apache-tomcat-7.0.40/webapps/docs/architecture
/apps/apache-tomcat-7.0.40/webapps/docs/architecture/startup
/apps/apache-tomcat-7.0.40/webapps/docs/architecture/startup/serverStartup.pdf
/apps/apache-tomcat-7.0.40/webapps/docs/architecture/startup/serverStartup.txt
/apps/apache-tomcat-7.0.40/webapps/docs/architecture/startup.html
/apps/apache-tomcat-7.0.40/webapps/docs/architecture/index.html
/apps/apache-tomcat-7.0.40/webapps/docs/architecture/requestProcess
/apps/apache-tomcat-7.0.40/webapps/docs/architecture/requestProcess/requestProcess.pdf
/apps/apache-tomcat-7.0.40/webapps/docs/architecture/requestProcess/roseModel.mdl
/apps/apache-tomcat-7.0.40/webapps/docs/architecture/overview.html
/apps/apache-tomcat-7.0.40/webapps/docs/architecture/requestProcess.html
/apps/apache-tomcat-7.0.40/webapps/docs/index.html
/apps/apache-tomcat-7.0.40/webapps/docs/building.html
/apps/apache-tomcat-7.0.40/webapps/docs/realm-howto.html
/apps/apache-tomcat-7.0.40/webapps/docs/jspapi
/apps/apache-tomcat-7.0.40/webapps/docs/jspapi/index.html
/apps/apache-tomcat-7.0.40/webapps/docs/deployer-howto.html
/apps/apache-tomcat-7.0.40/webapps/docs/images
/apps/apache-tomcat-7.0.40/webapps/docs/images/design.gif
/apps/apache-tomcat-7.0.40/webapps/docs/images/void.gif
/apps/apache-tomcat-7.0.40/webapps/docs/images/asf-logo.gif
/apps/apache-tomcat-7.0.40/webapps/docs/images/fix.gif
/apps/apache-tomcat-7.0.40/webapps/docs/images/tomcat.gif
/apps/apache-tomcat-7.0.40/webapps/docs/images/docs.gif
/apps/apache-tomcat-7.0.40/webapps/docs/images/tomcat.svg
/apps/apache-tomcat-7.0.40/webapps/docs/images/printer.gif
/apps/apache-tomcat-7.0.40/webapps/docs/images/update.gif
/apps/apache-tomcat-7.0.40/webapps/docs/images/code.gif
/apps/apache-tomcat-7.0.40/webapps/docs/images/add.gif
/apps/apache-tomcat-7.0.40/webapps/docs/logging.html
/apps/apache-tomcat-7.0.40/webapps/docs/BUILDING.txt
/apps/apache-tomcat-7.0.40/webapps/docs/developers.html
/apps/apache-tomcat-7.0.40/webapps/docs/monitoring.html
/apps/apache-tomcat-7.0.40/webapps/docs/connectors.html
/apps/apache-tomcat-7.0.40/webapps/docs/comments.html
/apps/apache-tomcat-7.0.40/webapps/docs/servletapi
/apps/apache-tomcat-7.0.40/webapps/docs/servletapi/index.html
/apps/apache-tomcat-7.0.40/webapps/docs/html-manager-howto.html
/apps/apache-tomcat-7.0.40/webapps/docs/config
/apps/apache-tomcat-7.0.40/webapps/docs/config/resources.html
/apps/apache-tomcat-7.0.40/webapps/docs/config/engine.html
/apps/apache-tomcat-7.0.40/webapps/docs/config/cluster-valve.html
/apps/apache-tomcat-7.0.40/webapps/docs/config/cluster.html
/apps/apache-tomcat-7.0.40/webapps/docs/config/cluster-manager.html
/apps/apache-tomcat-7.0.40/webapps/docs/config/valve.html
/apps/apache-tomcat-7.0.40/webapps/docs/config/cluster-receiver.html
/apps/apache-tomcat-7.0.40/webapps/docs/config/cluster-interceptor.html
/apps/apache-tomcat-7.0.40/webapps/docs/config/globalresources.html
/apps/apache-tomcat-7.0.40/webapps/docs/config/host.html
/apps/apache-tomcat-7.0.40/webapps/docs/config/ajp.html
/apps/apache-tomcat-7.0.40/webapps/docs/config/manager.html
/apps/apache-tomcat-7.0.40/webapps/docs/config/jar-scanner.html
/apps/apache-tomcat-7.0.40/webapps/docs/config/context.html
/apps/apache-tomcat-7.0.40/webapps/docs/config/index.html
/apps/apache-tomcat-7.0.40/webapps/docs/config/realm.html
/apps/apache-tomcat-7.0.40/webapps/docs/config/server.html
/apps/apache-tomcat-7.0.40/webapps/docs/config/cluster-listener.html
/apps/apache-tomcat-7.0.40/webapps/docs/config/loader.html
/apps/apache-tomcat-7.0.40/webapps/docs/config/service.html
/apps/apache-tomcat-7.0.40/webapps/docs/config/filter.html
/apps/apache-tomcat-7.0.40/webapps/docs/config/cluster-membership.html
/apps/apache-tomcat-7.0.40/webapps/docs/config/listeners.html
/apps/apache-tomcat-7.0.40/webapps/docs/config/cluster-channel.html
/apps/apache-tomcat-7.0.40/webapps/docs/config/cluster-sender.html
/apps/apache-tomcat-7.0.40/webapps/docs/config/cluster-deployer.html
/apps/apache-tomcat-7.0.40/webapps/docs/config/http.html
/apps/apache-tomcat-7.0.40/webapps/docs/config/executor.html
/apps/apache-tomcat-7.0.40/webapps/docs/config/systemprops.html
/apps/apache-tomcat-7.0.40/webapps/docs/windows-service-howto.html
/apps/apache-tomcat-7.0.40/webapps/docs/jasper-howto.html
/apps/apache-tomcat-7.0.40/webapps/docs/cgi-howto.html
/apps/apache-tomcat-7.0.40/webapps/docs/api
/apps/apache-tomcat-7.0.40/webapps/docs/api/index.html
/apps/apache-tomcat-7.0.40/webapps/docs/appdev
/apps/apache-tomcat-7.0.40/webapps/docs/appdev/sample
/apps/apache-tomcat-7.0.40/webapps/docs/appdev/sample/sample.war
/apps/apache-tomcat-7.0.40/webapps/docs/appdev/sample/web
/apps/apache-tomcat-7.0.40/webapps/docs/appdev/sample/web/WEB-INF
/apps/apache-tomcat-7.0.40/webapps/docs/appdev/sample/web/WEB-INF/web.xml
/apps/apache-tomcat-7.0.40/webapps/docs/appdev/sample/web/index.html
/apps/apache-tomcat-7.0.40/webapps/docs/appdev/sample/web/images
/apps/apache-tomcat-7.0.40/webapps/docs/appdev/sample/web/images/tomcat.gif
/apps/apache-tomcat-7.0.40/webapps/docs/appdev/sample/web/hello.jsp
/apps/apache-tomcat-7.0.40/webapps/docs/appdev/sample/index.html
/apps/apache-tomcat-7.0.40/webapps/docs/appdev/sample/src
/apps/apache-tomcat-7.0.40/webapps/docs/appdev/sample/src/mypackage
/apps/apache-tomcat-7.0.40/webapps/docs/appdev/sample/src/mypackage/Hello.java
/apps/apache-tomcat-7.0.40/webapps/docs/appdev/sample/docs
/apps/apache-tomcat-7.0.40/webapps/docs/appdev/sample/docs/README.txt
/apps/apache-tomcat-7.0.40/webapps/docs/appdev/sample/build.xml
/apps/apache-tomcat-7.0.40/webapps/docs/appdev/web.xml.txt
/apps/apache-tomcat-7.0.40/webapps/docs/appdev/deployment.html
/apps/apache-tomcat-7.0.40/webapps/docs/appdev/introduction.html
/apps/apache-tomcat-7.0.40/webapps/docs/appdev/index.html
/apps/apache-tomcat-7.0.40/webapps/docs/appdev/processes.html
/apps/apache-tomcat-7.0.40/webapps/docs/appdev/installation.html
/apps/apache-tomcat-7.0.40/webapps/docs/appdev/source.html
/apps/apache-tomcat-7.0.40/webapps/docs/appdev/build.xml.txt
/apps/apache-tomcat-7.0.40/webapps/docs/extras.html
/apps/apache-tomcat-7.0.40/webapps/docs/apr.html
/apps/apache-tomcat-7.0.40/webapps/docs/balancer-howto.html
/apps/apache-tomcat-7.0.40/temp
/apps/apache-tomcat-7.0.40/temp/safeToDelete.tmp
/apps/apache-tomcat-7.0.40/NOTICE
/apps/apache-tomcat-7.0.40/conf
/apps/apache-tomcat-7.0.40/conf/logging.properties
/apps/apache-tomcat-7.0.40/conf/context.xml
/apps/apache-tomcat-7.0.40/conf/web.xml
/apps/apache-tomcat-7.0.40/conf/server.xml
/apps/apache-tomcat-7.0.40/conf/catalina.properties
/apps/apache-tomcat-7.0.40/conf/tomcat-users.xml
/apps/apache-tomcat-7.0.40/conf/catalina.policy
/apps/apache-tomcat-7.0.40/RUNNING.txt
/apps/apache-tomcat-7.0.40/RELEASE-NOTES
/apps/apache-tomcat-7.0.40/lib
/apps/apache-tomcat-7.0.40/lib/tomcat-i18n-es.jar
/apps/apache-tomcat-7.0.40/lib/tomcat-i18n-ja.jar
/apps/apache-tomcat-7.0.40/lib/el-api.jar
/apps/apache-tomcat-7.0.40/lib/tomcat-dbcp.jar
/apps/apache-tomcat-7.0.40/lib/tomcat-jdbc.jar
/apps/apache-tomcat-7.0.40/lib/jasper-el.jar
/apps/apache-tomcat-7.0.40/lib/tomcat-coyote.jar
/apps/apache-tomcat-7.0.40/lib/tomcat-util.jar
/apps/apache-tomcat-7.0.40/lib/jsp-api.jar
/apps/apache-tomcat-7.0.40/lib/ecj-4.2.2.jar
/apps/apache-tomcat-7.0.40/lib/annotations-api.jar
/apps/apache-tomcat-7.0.40/lib/tomcat-i18n-fr.jar
/apps/apache-tomcat-7.0.40/lib/tomcat-api.jar
/apps/apache-tomcat-7.0.40/lib/jasper.jar
/apps/apache-tomcat-7.0.40/lib/catalina.jar
/apps/apache-tomcat-7.0.40/lib/catalina-ha.jar
/apps/apache-tomcat-7.0.40/lib/servlet-api.jar
/apps/apache-tomcat-7.0.40/lib/catalina-ant.jar
/apps/apache-tomcat-7.0.40/lib/catalina-tribes.jar
/apps/apache-tomcat-7.0.40/LICENSE
/apps/apache-tomcat-7.0.40/bin
/apps/apache-tomcat-7.0.40/bin/bootstrap.jar
/apps/apache-tomcat-7.0.40/bin/catalina.sh
/apps/apache-tomcat-7.0.40/bin/configtest.sh
/apps/apache-tomcat-7.0.40/bin/setclasspath.sh
/apps/apache-tomcat-7.0.40/bin/commons-daemon.jar
/apps/apache-tomcat-7.0.40/bin/tool-wrapper.sh
/apps/apache-tomcat-7.0.40/bin/cpappend.bat
/apps/apache-tomcat-7.0.40/bin/digest.bat
/apps/apache-tomcat-7.0.40/bin/shutdown.bat
/apps/apache-tomcat-7.0.40/bin/catalina-tasks.xml
/apps/apache-tomcat-7.0.40/bin/shutdown.sh
/apps/apache-tomcat-7.0.40/bin/tomcat-native.tar.gz
/apps/apache-tomcat-7.0.40/bin/startup.bat
/apps/apache-tomcat-7.0.40/bin/version.bat
/apps/apache-tomcat-7.0.40/bin/commons-daemon-native.tar.gz
/apps/apache-tomcat-7.0.40/bin/startup.sh
/apps/apache-tomcat-7.0.40/bin/setclasspath.bat
/apps/apache-tomcat-7.0.40/bin/digest.sh
/apps/apache-tomcat-7.0.40/bin/tool-wrapper.bat
/apps/apache-tomcat-7.0.40/bin/tomcat-juli.jar
/apps/apache-tomcat-7.0.40/bin/configtest.bat
/apps/apache-tomcat-7.0.40/bin/version.sh
/apps/apache-tomcat-7.0.40/bin/daemon.sh
/apps/apache-tomcat-7.0.40/bin/catalina.bat
/apps/apache-tomcat-7.0.40/logs
