/apps canfs02.cai.compute.pgs.com:/vol/apps
/cm canfs02.cai.compute.pgs.com:/vol/cm
/datadb canfs02.cai.compute.pgs.com:/vol/datadb
/group01 canfs01.cai.compute.pgs.com:/vol/group01
/group02 canfs01.cai.compute.pgs.com:/vol/group02
/group03 canfs01.cai.compute.pgs.com:/vol/group03
/group04 canfs01.cai.compute.pgs.com:/vol/group04
/group05 canfs01.cai.compute.pgs.com:/vol/group05
/group06_lon canfs01.cai.compute.pgs.com:/vol/group06_lon
/pgs canfs01.cai.compute.pgs.com:/vol/pgs
/tps canfs02.cai.compute.pgs.com:/vol/tps
/users canfs02.cai.compute.pgs.com:/vol/users
