#!/bin/bash

if [[ "$@" != "cfengine" ]]; then
	what_ran_me='cron'
else
	what_ran_me='cfengine'
fi
hostname=`hostname -f`;
ip=`hostname -i`;
release=`cat /etc/redhat-release`;
kernel=`uname -r`;
arch=`uname -i`;
product_name=`/usr/sbin/dmidecode -s system-product-name`;
release_date=`/usr/sbin/dmidecode -s bios-release-date`;
serial_number=`/usr/sbin/dmidecode -s system-serial-number`;
line_speed=`/sbin/ethtool eth0|/bin/grep Speed | /bin/awk '{print $2}'`;
user=`/usr/bin/who | /bin/awk '{print $1}' | /bin/sort -u | /bin/grep -v root | /bin/awk '{print "/opt/likewise/bin/lw-find-user-by-name ",$1,"--level 2"}' | /bin/sh | /bin/grep PGS.COM | /bin/awk '{print $2}'`
video_card=`/sbin/lspci |grep -i vga | cut -f3 -d:`;
memory=`/usr/bin/free -m | /bin/grep Mem | /usr/bin/awk '{print $2}'`;
panels=`nvidia-xconfig --query-gpu-info | /bin/grep EDID | cut -f2 -d:`;
res=`/bin/grep -i virtual\ screen /var/log/Xorg.0.log | /usr/bin/awk '{print $12$13$14}'`;

sql="replace into systems values('','$hostname','$ip','$release','$kernel','$arch','$product_name','$serial_number','$line_speed','$memory','$user','$video_card','$panels $res', NOW(), '$what_ran_me', '$release_date')";

sleep $((RANDOM%200+90))
mysql -u inventory -D inventory -h pinky.onshore.pgs.com -e "$sql";
